<?php

namespace AppBundle\Entity\Repository;

/**
 * SalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestSales($limit = null)
    {
        $qd = $this->createQueryBuilder('s')
                    ->select('s');
        if(is_null($limit) === false)
        {
            $qd->setMaxResults($limit);
        }
        return $qd->getQuery()->getResult();
    }
}
